### PR TITLE
toggleable usergroup list

### PR DESCRIPTION
**Pull request by NC-jsAhonen**
The new usergroup list looks as follows. It is toggled using the info icon. I could not find a person icon and the icons are created in the mvj-ui as manually inserted vector values, so it would take extra work to make it into a person icon. Is info icon good enough in your opinion?

image

### CODE REVIEW

**Comment by robertrytovuori** [comment]
Have you tried looking online for free person icons? I found for example this: https://www.svgrepo.com/svg/506667/person

**Comment by NC-jsAhonen** [comment]
> Have you tried looking online for free person icons? I found for example this: https://www.svgrepo.com/svg/506667/person

No, because I am also wondering whether info icon is a better idea that a person icon, given that the only thing it does is give some info. It is not a regular user account dropdown menu, so I am a bit doubtful whether info or person icon is better.

**Comment by henrinie-nc** [comment]
Should we use HDS icons in case we migrate to use HDS at some stage?
https://hds.hel.fi/foundation/visual-assets/icons/list/

**Review by robertrytovuori — APPROVED** [review]

**Comment by NC-jsAhonen** [comment]
image

**Pull request merged**
